Stardew Valley:
  accessibility: items
  goal:
    community_center: 50
    grandpa_evaluation: 25
    bottom_of_the_mines: 2
    master_angler: 2
    complete_collection: 2
    protector_of_the_valley: 2
    full_shipment: 2
    gourmet_chef: 2
    craft_master: 2
    legend: 2
    mystery_of_the_stardrops: 10
  farm_type: random
  starting_money: random-range-1000-25000
  profit_margin:
    normal: 30
    double: 40
    triple: 20
    quadruple: 10
  bundle_randomization:
    vanilla: 5
    thematic: 15
    remixed: 75
    shuffled: 5
  bundle_price:
    minimum: 5
    very_cheap: 15
    cheap: 50
    normal: 25
    expensive: 5
  entrance_randomization:
    disabled: 50
    pelican_town: 10
    non_progression: 20
    buildings: 20
  season_randomization:
    randomized: 40
    randomized_not_winter: 40
    progressive: 20
  cropsanity: enabled
  backpack_progression: early_progressive
  tool_progression:
    progressive_very_cheap: 30
    progressive_cheap: 40
    progressive: 30
  elevator_progression:
    progressive: 50
    progressive_from_previous_floor: 50
  skill_progression: progressive
  building_progression:
    progressive_very_cheap: 40
    progressive_cheap: 40
    progressive: 20
  festival_locations:
    disabled: 20
    easy: 40
    hard: 40
  arcade_machine_locations: disabled
  special_order_locations:
    disabled: 40
    board_only: 40
    board_qi: 20
  quest_locations:
    0: 50
    7: 25
    14: 25
  fishsanity:
    none: 10
    exclude_legendaries: 20
    exclude_hard_fish: 50
    only_easy_fish: 20
  museumsanity:
    none: 60
    milestones: 30
    all: 10
  monstersanity:
    one_per_category: 25
    one_per_monster: 25
    very_short_goals: 20
    short_goals: 20
    progressive_goals: 5
    split_goals: 5
  shipsanity:
    none: 80
    crops: 15
    full_shipment: 5
  cooksanity:
    none: 70
    queen_of_sauce: 20
    all: 10
  chefsanity:
    none: 70
    queen_of_sauce: 20
    all: 10
  craftsanity:
    none: 80
    all: 20
  friendsanity:
    none: 40
    bachelors: 25
    starting_npcs: 25
    all: 10
  friendsanity_heart_size: random-range-3-5
  movement_buff_number: random-range-4-8
  luck_buff_number: random-range-4-12
  exclude_ginger_island:
    false: 50
    true: 50
  trap_items:
    no_traps: 15
    easy: 50
    medium: 25
    hard: 10
  multiple_day_sleep_enabled: 'true'
  multiple_day_sleep_cost: 0
  experience_multiplier:
    double: 50
    triple: 40
    quadruple: 10
  friendship_multiplier:
    double: 20
    triple: 50
    quadruple: 30
  debris_multiplier:
    vanilla: 25
    half: 50
    quarter: 25
  quick_start: 'true'
  gifting: 'true'
  mods: []
  death_link: 'false'
triggers: #Added triggers to complement the goal (eg. add museumsanity to a museum goal)
    - option_category: Stardew Valley
      option_name: goal
      option_result: community_center
      options:
        Stardew Valley:
          bundle_price: #Move minimal odds to very_expensive odds
            very_cheap: 15
            cheap: 50
            normal: 25
            expensive: 5
            very_expensive: 5
    - option_category: Stardew Valley
      option_name: goal
      option_result: master_angler #catch all fishsanity fish
      options:
        Stardew Valley:
          fishsanity: #Move none odds to all
            all: 10
            exclude_legendaries: 20
            exclude_hard_fish: 50
            only_easy_fish: 20
    - option_category: Stardew Valley
      option_name: goal
      option_result: complete_collection #finish museum
      options:
        Stardew Valley:
          museumsanity: #remove none odds
            milestones: 30
            all: 10
    - option_category: Stardew Valley
      option_name: goal
      option_result: full_shipment # ship all items, follows shipsanity
      options:
        Stardew Valley:
          shipsanity: #Remove none odds
            crops: 15
            full_shipment: 5
    - option_category: Stardew Valley
      option_name: goal
      option_result: gourmet_chef # cook every recipe, follows cooksanity
      options:
        Stardew Valley:
          cooksanity: #Remove none odds
            queen_of_sauce: 20
            all: 10
          chefsanity: #Increase the odds shuffling recipes to add
            none: 10
            all: 10
            random: 10
    - option_category: Stardew Valley
      option_name: goal
      option_result: craft_master #craft every item
      options:
        Stardew Valley:
          craftsanity: #Remove none odds
            all: 20
    - option_category: Stardew Valley
      option_name: goal
      option_result: protector_of_the_valley # complete monsterslayer goals, follows monstersanity
      options: 
        Stardew Valley: #Remove one_per_category odds
          monstersanity:
            one_per_monster: 25
            very_short_goals: 20
            short_goals: 20
            progressive_goals: 5
            split_goals: 5
    - option_category: Stardew Valley
      option_name: goal
      option_result: mystery_of_the_stardrops #find every stardrop
      options:
        Stardew Valley:
          museumsanity: #Remove none odds
            milestones: 30
            all: 10
          festival_locations: #Remove disable odds
            easy: 40
            hard: 40
          friendsanity: #Remove none odds
            bachelors: 25
            starting_npcs: 25
            all: 10
          fishsanity: #Set to all, since that is required
            all: 10
